################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/client.c \
/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/helpers.c \
/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/packet.c \
/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/string.c 

C_DEPS += \
./libraries/MQTT/src/lwmqtt/client.c.d \
./libraries/MQTT/src/lwmqtt/helpers.c.d \
./libraries/MQTT/src/lwmqtt/packet.c.d \
./libraries/MQTT/src/lwmqtt/string.c.d 

LINK_OBJ += \
./libraries/MQTT/src/lwmqtt/client.c.o \
./libraries/MQTT/src/lwmqtt/helpers.c.o \
./libraries/MQTT/src/lwmqtt/packet.c.o \
./libraries/MQTT/src/lwmqtt/string.c.o 


# Each subdirectory must supply rules for building sources it contributes
libraries/MQTT/src/lwmqtt/client.c.o: /home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/client.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-gcc" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-I/home/danielyeste/Documents/sloeber-workspace/OTA_Testing/Release/core" -c -w -Werror=return-type -std=gnu17  -Os -g -free -fipa-pta -Wpointer-arith -Wno-implicit-function-declaration -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -falign-functions=4 -MMD -ffunction-sections -fdata-sections -fno-exceptions  -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000  -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0  -DDEBUG_ESP_SSL -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_SERVER -DARDUINO=10812 -DARDUINO_ESP8266_ADAFRUIT_HUZZAH -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_ADAFRUIT_HUZZAH\""  -DFLASHMODE_QIO  -DESP8266   -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/variants/adafruit" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/esp8266/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/WiFiManager/2.0.9-beta" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/DNSServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClientTools/0.6.0" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClient/2.8.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/SPI" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/Wire" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/DFRobot_CCS811/1.0.1" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/MQTT/src/lwmqtt/helpers.c.o: /home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/helpers.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-gcc" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-I/home/danielyeste/Documents/sloeber-workspace/OTA_Testing/Release/core" -c -w -Werror=return-type -std=gnu17  -Os -g -free -fipa-pta -Wpointer-arith -Wno-implicit-function-declaration -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -falign-functions=4 -MMD -ffunction-sections -fdata-sections -fno-exceptions  -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000  -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0  -DDEBUG_ESP_SSL -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_SERVER -DARDUINO=10812 -DARDUINO_ESP8266_ADAFRUIT_HUZZAH -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_ADAFRUIT_HUZZAH\""  -DFLASHMODE_QIO  -DESP8266   -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/variants/adafruit" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/esp8266/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/WiFiManager/2.0.9-beta" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/DNSServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClientTools/0.6.0" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClient/2.8.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/SPI" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/Wire" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/DFRobot_CCS811/1.0.1" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/MQTT/src/lwmqtt/packet.c.o: /home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/packet.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-gcc" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-I/home/danielyeste/Documents/sloeber-workspace/OTA_Testing/Release/core" -c -w -Werror=return-type -std=gnu17  -Os -g -free -fipa-pta -Wpointer-arith -Wno-implicit-function-declaration -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -falign-functions=4 -MMD -ffunction-sections -fdata-sections -fno-exceptions  -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000  -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0  -DDEBUG_ESP_SSL -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_SERVER -DARDUINO=10812 -DARDUINO_ESP8266_ADAFRUIT_HUZZAH -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_ADAFRUIT_HUZZAH\""  -DFLASHMODE_QIO  -DESP8266   -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/variants/adafruit" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/esp8266/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/WiFiManager/2.0.9-beta" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/DNSServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClientTools/0.6.0" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClient/2.8.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/SPI" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/Wire" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/DFRobot_CCS811/1.0.1" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/MQTT/src/lwmqtt/string.c.o: /home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src/lwmqtt/string.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-gcc" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include" "-I/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-I/home/danielyeste/Documents/sloeber-workspace/OTA_Testing/Release/core" -c -w -Werror=return-type -std=gnu17  -Os -g -free -fipa-pta -Wpointer-arith -Wno-implicit-function-declaration -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -falign-functions=4 -MMD -ffunction-sections -fdata-sections -fno-exceptions  -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000  -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0  -DDEBUG_ESP_SSL -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_SERVER -DARDUINO=10812 -DARDUINO_ESP8266_ADAFRUIT_HUZZAH -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_ADAFRUIT_HUZZAH\""  -DFLASHMODE_QIO  -DESP8266   -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/variants/adafruit" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/esp8266/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/WiFiManager/2.0.9-beta" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/DNSServer/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClientTools/0.6.0" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/PubSubClient/2.8.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/MQTT/2.5.0/src" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/SPI" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/3.0.2/libraries/Wire" -I"/home/danielyeste/Desktop/Sloeber/arduinoPlugin/libraries/DFRobot_CCS811/1.0.1" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '


